<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Upazilas\Upazilas>
 */
class UpazilasFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $data =[
            ["id"=>1,"division_id"=>3,"district_id"=>1,"bn_name"=>"পল্টন থানা","name"=>"Palton Thana"],
            ["id"=>2,"division_id"=>3,"district_id"=>1,"bn_name"=>"সূত্রাপুর থানা","name"=>"Sutrapur Thana"],
            ["id"=>3,"division_id"=>3,"district_id"=>1,"bn_name"=>"চকবাজার থানা","name"=>"Chalk Bazar Thana"],
            ["id"=>4,"division_id"=>3,"district_id"=>1,"bn_name"=>"হাজারীবাগ থানা","name"=>"Hazaribag Thana"],
            ["id"=>5,"division_id"=>3,"district_id"=>1,"bn_name"=>"লালবাগ থানা","name"=>"Lalbag Thana"],
            ["id"=>6,"division_id"=>3,"district_id"=>1,"bn_name"=>"কোতোয়ালী থানা ","name"=>"Kutuali Thana"],
            ["id"=>7,"division_id"=>3,"district_id"=>1,"bn_name"=>"গেন্ডারিয়া থানা","name"=>"Gendaria Thana"],
            ["id"=>8,"division_id"=>3,"district_id"=>1,"bn_name"=>"যাত্রাবাড়ী থানা","name"=>"Jatrabari Thana"],
            ["id"=>9,"division_id"=>3,"district_id"=>1,"bn_name"=>"ওয়ারী থানা","name"=>"Wari Thana"],
            ["id"=>10,"division_id"=>3,"district_id"=>1,"bn_name"=>"বংশাল থানা","name"=>"Bongshal Thana"],
//                ["id"=>92,"division_id"=>3,"district_id"=>1,"bn_name"=>"সূত্রাপুর থানা","name"=>"Sutrapur Thana"],
            ["id"=>11,"division_id"=>3,"district_id"=>1,"bn_name"=>"শ্যামপুর থানা","name"=>"Sampur Thana"],
            ["id"=>12,"division_id"=>3,"district_id"=>1,"bn_name"=>"কদমতলী থানা","name"=>"Kadamtoli Thana"],
            ["id"=>13,"division_id"=>3,"district_id"=>1,"bn_name"=>"মতিঝিল থানা","name"=>"Motijheel Thana"],
            ["id"=>14,"division_id"=>3,"district_id"=>1,"bn_name"=>"নিউ মার্কেট থানা","name"=>"Newmarket Thana"],
            ["id"=>15,"division_id"=>3,"district_id"=>1,"bn_name"=>"হাতিরঝিল থানা","name"=>"Hatir Jheel Thana"],
            ["id"=>16,"division_id"=>3,"district_id"=>1,"bn_name"=>"বনানী থানা","name"=>"Banani Thana"],
            ["id"=>17,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Palton Thana"],
            ["id"=>18,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Shahbag Thana"],
            ["id"=>19,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Cantonment Thana"],
            ["id"=>20,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Ramna Thana"],
            ["id"=>21,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Muhammadpur  Thana"],
            ["id"=>22,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Tejgaon Thana"],
            ["id"=>23,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Motijheel Thana"],
            ["id"=>24,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Kasrul Thana"],
            ["id"=>25,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Sher-E-Banglanagar Thana"],
            ["id"=>26,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Shahali Thana"],
            ["id"=>27,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Mirpur Thana"],
            ["id"=>28,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Badda Thana"],
            ["id"=>29,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Newmarket Thana"],
            ["id"=>30,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Hazaribagh Thana"],
            ["id"=>31,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Uttara West Thana"],
            ["id"=>32,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Tejgaon Industrial area Thana"],
            ["id"=>33,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Pallabi Thana"],
            ["id"=>34,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Gulshan Thana"],
            ["id"=>35,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Sobujbag Thana"],
            ["id"=>36,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Khilgaon Thana"],
            ["id"=>37,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Khilkhet Thana"],
            ["id"=>38,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Vatara Thana"],
            ["id"=>39,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Uttarkhan Thana"],
            ["id"=>40,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Rampura Thana"],
            ["id"=>41,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Mugda Thana"],
            ["id"=>42,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Dakshin Khan Thana"],
            ["id"=>43,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Turag Thana"],
            ["id"=>44,"division_id"=>3,"district_id"=>1,"bn_name"=>"দোহার উপজেলা","name"=>"Dohar Upazila "],
            ["id"=>45,"division_id"=>3,"district_id"=>1,"bn_name"=>"সাভার উপজেলা","name"=>"Savar Upazila"],
            ["id"=>46,"division_id"=>3,"district_id"=>1,"bn_name"=>"ধামরাই উপজেলা","name"=>"Dhamrai Upazila"],
            ["id"=>47,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Keraniganj Upazila"],
            ["id"=>48,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Nawabganj Upazila"],
            ["id"=>49,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Demra Thana"],
            ["id"=>50,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Jatrabari Thana"],
            ["id"=>51,"division_id"=>3,"district_id"=>1,"bn_name"=>"","name"=>"Kodomtoli Thana"],
//====================================================================================================================

//=================================== Faridpur District ==============================================================
            ["id"=>52,"division_id"=>3,"district_id"=>2,"bn_name"=>"ফরিদপুর সদর","name"=>"Faridpur Sadar Upazila"],
            ["id"=>53,"division_id"=>3,"district_id"=>2,"bn_name"=>"শালথা উপজেলা","name"=>"Saltha Upazila"],
            ["id"=>54,"division_id"=>3,"district_id"=>2,"bn_name"=>"চরভদ্রাসন উপজেলা","name"=>"Charbadrashan Upazila"],
            ["id"=>55,"division_id"=>3,"district_id"=>2,"bn_name"=>"সদরপুর উপজেলা","name"=>"Sadarpur Upazila"],
            ["id"=>56,"division_id"=>3,"district_id"=>2,"bn_name"=>"ভাঙ্গা উপজেলা","name"=>"Bhanga Upazila"],
            ["id"=>57,"division_id"=>3,"district_id"=>2,"bn_name"=>"নগরকান্ড উপজেলা","name"=>"Nagarkanda Upazila"],
            ["id"=>58,"division_id"=>3,"district_id"=>2,"bn_name"=>"মধুখালি উপজেলা","name"=>"Madukhali Upazila"],
            ["id"=>59,"division_id"=>3,"district_id"=>2,"bn_name"=>"বোয়ালমারী উপজেলা","name"=>"Boalmari Upazila"],
            ["id"=>60,"division_id"=>3,"district_id"=>2,"bn_name"=>"আলফাডাঙ্গা উপজেলা","name"=>"Alfadanganga Upazila"],
//======================================================================================================================

//=================================== Gazipur District =================================================================
            ["id"=>61,"division_id"=>3,"district_id"=>3,"bn_name"=>"গাজীপুর সদর উপজেলা","name"=>"Gazipur sadar"],
            ["id"=>62,"division_id"=>3,"district_id"=>3,"bn_name"=>"কালিগঞ্জ উপজেলা","name"=>"Kaliganj Upazila"],
            ["id"=>63,"division_id"=>3,"district_id"=>3,"bn_name"=>"কাপাসিয়া উপজেলা","name"=>"Kapasia  Upazila"],
            ["id"=>64,"division_id"=>3,"district_id"=>3,"bn_name"=>"শ্রীপুর উপজেলা","name"=>"Sreepur Upazila"],
            ["id"=>65,"division_id"=>3,"district_id"=>3,"bn_name"=>"কালিয়াকৈর উপজেলা","name"=>"Kaliakair  Upazila"],
//======================================================================================================================

//=================================== Gopalganj District ===============================================================
            ["id"=>66,"division_id"=>3,"district_id"=>4,"bn_name"=>"গোপালগঞ্জ সদর উপজেলা","name"=>"Gopalganj Sadar Upazila"],
            ["id"=>67,"division_id"=>3,"district_id"=>4,"bn_name"=>"কোটালীপাড়া উপজেলা","name"=>"Kotalipara Upazila"],
            ["id"=>68,"division_id"=>3,"district_id"=>4,"bn_name"=>"টুঙ্গিপাড়া উপজেলা","name"=>"Tungipara Upazila"],
            ["id"=>69,"division_id"=>3,"district_id"=>4,"bn_name"=>"কাশিয়ানী উপজেলা","name"=>"Kashiani Upazila"],
            ["id"=>70,"division_id"=>3,"district_id"=>4,"bn_name"=>"মুকসুদপুর উপজেলা","name"=>"Maksudpur Upazila"],
//======================================================================================================================

//=================================== Kishoreganj District =============================================================
            ["id"=>71,"division_id"=>3,"district_id"=>6,"bn_name"=>"কিশোরগঞ্জ সদর উপজেলা","name"=>"Kishoreganj sadar"],
            ["id"=>72,"division_id"=>3,"district_id"=>6,"bn_name"=>"করিমগঞ্জ উপজেলা","name"=>"Karimganj Upazila"],
            ["id"=>73,"division_id"=>3,"district_id"=>6,"bn_name"=>"তাড়াইল উপজেলা","name"=>"Tarial Upazila"],
            ["id"=>74,"division_id"=>3,"district_id"=>6,"bn_name"=>"হোসেনপুর উপজেলা","name"=>"Hossenpur Upazila"],
            ["id"=>75,"division_id"=>3,"district_id"=>6,"bn_name"=>"পাকুন্দিয়া উপজেলা","name"=>"Pakundia Upazila"],
            ["id"=>76,"division_id"=>3,"district_id"=>6,"bn_name"=>"কটিয়াদী উপজেলা","name"=>"Katiadi Upazila"],
            ["id"=>77,"division_id"=>3,"district_id"=>6,"bn_name"=>"বাজিতপুর উপজেলা","name"=>"Bajitpur Upazila"],
            ["id"=>78,"division_id"=>3,"district_id"=>6,"bn_name"=>"কুলিয়ারচর উপজেলা","name"=>"Kuliarchar Upazila"],
            ["id"=>79,"division_id"=>3,"district_id"=>6,"bn_name"=>"ভৈরব উপজেলা","name"=>"Bhairab Upazila"],
            ["id"=>80,"division_id"=>3,"district_id"=>6,"bn_name"=>"নিকলী উপজেলা","name"=>"Nikli Upazila"],
            ["id"=>81,"division_id"=>3,"district_id"=>6,"bn_name"=>"মিঠামইন উপজেলা","name"=>"Mithamoin Upazila"],
            ["id"=>82,"division_id"=>3,"district_id"=>6,"bn_name"=>"অষ্টগ্রাম উপজেলা","name"=>"Ostagram Upazila"],
            ["id"=>83,"division_id"=>3,"district_id"=>6,"bn_name"=>"ইটনা উপজেলা","name"=>"Itna Upazila"],
//======================================================================================================================

//=================================== Madaripur District ===============================================================
            ["id"=>84,"division_id"=>3,"district_id"=>7,"bn_name"=>"মাদারীপুর সদর উপজেলা","name"=>"Madaripur Sadar Upazila"],
            ["id"=>85,"division_id"=>3,"district_id"=>7,"bn_name"=>"রাজৈর উপজেলা","name"=>"Rajoir Upazila"],
            ["id"=>86,"division_id"=>3,"district_id"=>7,"bn_name"=>"কালকিনি উপজেলা","name"=>"Kalkini Upazila"],
            ["id"=>87,"division_id"=>3,"district_id"=>7,"bn_name"=>"শিবচর উপজেলা","name"=>"Shibchar Upazila"],
//======================================================================================================================

//=================================== Manikganj District ===============================================================
            ["id"=>88,"division_id"=>3,"district_id"=>8,"bn_name"=>"মানিকগঞ্জ সদর উপজেলা","name"=>"Manikganj Sadar Upazila"],
            ["id"=>89,"division_id"=>3,"district_id"=>8,"bn_name"=>"সাটুরিয়া উপজেলা","name"=>"Saturia Upazila"],
            ["id"=>90,"division_id"=>3,"district_id"=>8,"bn_name"=>"সিংগাইর উপজেলা","name"=>"Singair Upazila"],
            ["id"=>91,"division_id"=>3,"district_id"=>8,"bn_name"=>"হরিরামপুর উপজেলা","name"=>"Hariampur Upazila"],
            ["id"=>92,"division_id"=>3,"district_id"=>8,"bn_name"=>"ঘিওর উপজেলা","name"=>"Gheor Upazila"],
            ["id"=>93,"division_id"=>3,"district_id"=>8,"bn_name"=>"শিবালয় উপজেলা","name"=>"Shibaloy Upazila"],
            ["id"=>94,"division_id"=>3,"district_id"=>8,"bn_name"=>"দৌলতপুর উপজেলা ","name"=>"Doulatpur"],
//======================================================================================================================
//=================================== Munshiganj District ==============================================================
            ["id"=>95,"division_id"=>3,"district_id"=>9,"bn_name"=>"মুন্সীগঞ্জ সদর উপজেলা","name"=>"Munshiganj sadar Upazila"],
            ["id"=>96,"division_id"=>3,"district_id"=>9,"bn_name"=>"গজারিয়া উপজেলা","name"=>"Gajaria Upazila"],
            ["id"=>97,"division_id"=>3,"district_id"=>9,"bn_name"=>"টংগিবাড়ী উপজেলা","name"=>"Tangibari Upazila"],
            ["id"=>98,"division_id"=>3,"district_id"=>9,"bn_name"=>"","name"=>"Lohajong Upazila"],
            ["id"=>99,"division_id"=>3,"district_id"=>9,"bn_name"=>"","name"=>"Sirajdikhan Upazila"],
            ["id"=>100,"division_id"=>3,"district_id"=>9,"bn_name"=>"","name"=>"Srinagar Upazila"],
//======================================================================================================================
//=================================== Narayanganj District =============================================================
            ["id"=>101,"division_id"=>3,"district_id"=>11,"bn_name"=>"নারায়নগঞ্জ সদর উপজেলা","name"=>"Narayanganj Sadar Upazila"],
            ["id"=>102,"division_id"=>3,"district_id"=>11,"bn_name"=>"বন্দর উপজেলা","name"=>"Bandar Upazila"],
            ["id"=>103,"division_id"=>3,"district_id"=>11,"bn_name"=>"আড়াইহাজার উপজেলা","name"=>"Araihazar Upazila"],
            ["id"=>104,"division_id"=>3,"district_id"=>11,"bn_name"=>"রূপগঞ্জ উপজেলা","name"=>"Rupganj Upazila"],
            ["id"=>105,"division_id"=>3,"district_id"=>11,"bn_name"=>"সোনারগাঁ উপজেলা","name"=>"Sonargaon Upazila"],
//======================================================================================================================
//=================================== Narshingdi District ==============================================================
            ["id"=>106,"division_id"=>3,"district_id"=>,"bn_name"=>"নরসিংদী সদর উপজেলা","name"=>"Narshingdi Sadar Upazila"],
            ["id"=>107,"division_id"=>3,"district_id"=>,"bn_name"=>"শিবপুর উপজেলা","name"=>"Shibpur Upazila"],
            ["id"=>108,"division_id"=>3,"district_id"=>,"bn_name"=>"বেলাবো উপজেলা","name"=>"Belabo Upazila"],
            ["id"=>109,"division_id"=>3,"district_id"=>,"bn_name"=>"মনোহরদী উপজেলা","name"=>"Monohordi Upazila"],
            ["id"=>110,"division_id"=>3,"district_id"=>,"bn_name"=>"পলাশ উপজেলা","name"=>"Palash Upazila"],
            ["id"=>111,"division_id"=>3,"district_id"=>,"bn_name"=>"রায়পুরা উপজেলা","name"=>"Raypura Upazila"],
//======================================================================================================================
//=================================== Rajbari District ================================================================
            ["id"=>112,"division_id"=>3,"district_id"=>14,"bn_name"=>"রাজবাড়ী সদর উপজেলা","name"=>"Rajbari Sadar Upazila"],
            ["id"=>113,"division_id"=>3,"district_id"=>14,"bn_name"=>"","name"=>"Goalanda Upazila"],
            ["id"=>114,"division_id"=>3,"district_id"=>14,"bn_name"=>"","name"=>"Pangsha Upazila"],
            ["id"=>115,"division_id"=>3,"district_id"=>14,"bn_name"=>"","name"=>"Kalukhali Upazila"],
            ["id"=>116,"division_id"=>3,"district_id"=>14,"bn_name"=>"","name"=>"Baliakandi Upazila"],
//======================================================================================================================
//=================================== Shariatpur District ==============================================================
            ["id"=>117,"division_id"=>3,"district_id"=>15,"bn_name"=>"","name"=>"Shariatpur Sadar Upazila"],
            ["id"=>118,"division_id"=>3,"district_id"=>15,"bn_name"=>"","name"=>"Jajira Upazila"],
            ["id"=>119,"division_id"=>3,"district_id"=>15,"bn_name"=>"","name"=>"Naria Upazila"],
            ["id"=>120,"division_id"=>3,"district_id"=>15,"bn_name"=>"","name"=>"Badarganj Upazila"],
            ["id"=>121,"division_id"=>3,"district_id"=>15,"bn_name"=>"","name"=>"Badarganj Upazila"],
            ["id"=>122,"division_id"=>3,"district_id"=>15,"bn_name"=>"","name"=>"Damudya Upazila"],
            ["id"=>123,"division_id"=>3,"district_id"=>15,"bn_name"=>"","name"=>"Gosairhat Upazila"],
//======================================================================================================================
//=================================== Tangail District =================================================================
            ["id"=>124,"division_id"=>3,"district_id"=>17,"bn_name"=>"","name"=>"Tangail sadar Upazila"],
            ["id"=>125,"division_id"=>3,"district_id"=>17,"bn_name"=>"","name"=>"Delduar Upazila"],
            ["id"=>126,"division_id"=>3,"district_id"=>17,"bn_name"=>"","name"=>"Basail Upazila"],
            ["id"=>127,"division_id"=>3,"district_id"=>17,"bn_name"=>"","name"=>"Nagarpur Upazila"],
            ["id"=>128,"division_id"=>3,"district_id"=>17,"bn_name"=>"","name"=>"Mirzapur Upazila"],
            ["id"=>129,"division_id"=>3,"district_id"=>17,"bn_name"=>"","name"=>"Sakhipur Upazila"],
            ["id"=>130,"division_id"=>3,"district_id"=>17,"bn_name"=>"","name"=>"Bhuapur Upazila"],
            ["id"=>131,"division_id"=>3,"district_id"=>17,"bn_name"=>"","name"=>"Kalihati Upazila"],
            ["id"=>132,"division_id"=>3,"district_id"=>17,"bn_name"=>"","name"=>"Ghatail Upazila"],
            ["id"=>133,"division_id"=>3,"district_id"=>17,"bn_name"=>"","name"=>"Gopalpur Upazila"],
            ["id"=>134,"division_id"=>3,"district_id"=>17,"bn_name"=>"","name"=>"Madhupur Upazila"],
            ["id"=>135,"division_id"=>3,"district_id"=>17,"bn_name"=>"","name"=>"Dhonbari Upazila"],
//======================================================================================================================
//=================================== Bandarban District ==============================================================
            ["id"=>136,"division_id"=>2,"district_id"=>40,"bn_name"=>"","name"=>"Bandorban Sadar"],
            ["id"=>137,"division_id"=>2,"district_id"=>40,"bn_name"=>"","name"=>"Ruma Upazila "],
            ["id"=>138,"division_id"=>2,"district_id"=>40,"bn_name"=>"","name"=>"Thanchi Upazila "],
            ["id"=>139,"division_id"=>2,"district_id"=>40,"bn_name"=>"","name"=>"Lama Upazila "],
            ["id"=>140,"division_id"=>2,"district_id"=>40,"bn_name"=>"","name"=>"Rowangchari Upazila"],
            ["id"=>141,"division_id"=>2,"district_id"=>40,"bn_name"=>"","name"=>"Alikadam Upazila"],
            ["id"=>142,"division_id"=>2,"district_id"=>40,"bn_name"=>"","name"=>"Naikhyongcharl Upazila"],
//======================================================================================================================
//=================================== Brahmanbaria District ===========================================================
            ["id"=>143,"division_id"=>2,"district_id"=>41,"bn_name"=>"","name"=>"Brahmanbaria Sadar Upazila"],
            ["id"=>144,"division_id"=>2,"district_id"=>41,"bn_name"=>"","name"=>"Ashuganj Upazila"],
            ["id"=>145,"division_id"=>2,"district_id"=>41,"bn_name"=>"","name"=>"Nabinagar Upazila"],
            ["id"=>146,"division_id"=>2,"district_id"=>41,"bn_name"=>"","name"=>"Banchharampur Upzia"],
            ["id"=>147,"division_id"=>2,"district_id"=>41,"bn_name"=>"","name"=>"Sarail Upzila"],
            ["id"=>148,"division_id"=>2,"district_id"=>41,"bn_name"=>"","name"=>"Nasirnagar Upazila"],
            ["id"=>149,"division_id"=>2,"district_id"=>41,"bn_name"=>"","name"=>"Akhaura Upazila"],
            ["id"=>150,"division_id"=>2,"district_id"=>41,"bn_name"=>"","name"=>"Kasba Upazila"],
            ["id"=>151,"division_id"=>2,"district_id"=>41,"bn_name"=>"","name"=>"Bijoynagar Upazila"],
//======================================================================================================================
//=================================== Chandpur District ==============================================================
            ["id"=>152,"division_id"=>2,"district_id"=>42,"bn_name"=>"","name"=>"Chandpur Sadar Upazila"],
            ["id"=>153,"division_id"=>2,"district_id"=>42,"bn_name"=>"","name"=>"Shahrasti Upazila"],
            ["id"=>154,"division_id"=>2,"district_id"=>42,"bn_name"=>"","name"=>"Motlob dokkhin Upazila"],
            ["id"=>155,"division_id"=>2,"district_id"=>42,"bn_name"=>"","name"=>"Motlob uttor Upazila"],
            ["id"=>156,"division_id"=>2,"district_id"=>42,"bn_name"=>"","name"=>"Faridgonj Upazila"],
            ["id"=>157,"division_id"=>2,"district_id"=>42,"bn_name"=>"","name"=>"Kachua Upazila"],
            ["id"=>158,"division_id"=>2,"district_id"=>42,"bn_name"=>"","name"=>"Haimchar Upazila"],
            ["id"=>159,"division_id"=>2,"district_id"=>42,"bn_name"=>"","name"=>"Hazigonj Upazila"],
//======================================================================================================================
//=================================== Chattogram District ==============================================================
            ["id"=>160,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Kotwali Thana"],
            ["id"=>161,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Double Mooring Thana"],
            ["id"=>162,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Akbarshah Thana"],
            ["id"=>163,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Patenga Thana"],
            ["id"=>164,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Pahartoli Thana"],
            ["id"=>165,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Bayazid Thana"],
            ["id"=>166,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Chandgaon Thana"],
            ["id"=>167,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Halishahar Thana"],
            ["id"=>168,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Bandar Thana"],
            ["id"=>169,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"EPZ Thana"],
            ["id"=>170,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Chawkbazar Thana"],
            ["id"=>171,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Panchlaaish Thana"],
            ["id"=>172,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Khulsi Thana"],
            ["id"=>173,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Karnaphuli Upazila"],
            ["id"=>174,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Chandanish Upazila"],
            ["id"=>175,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Patia Upazila"],
            ["id"=>176,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Anowara Upazila"],
            ["id"=>177,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Boalkhali Upazila"],
            ["id"=>178,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Rouzan Upazila"],
            ["id"=>179,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Hathazari Upizala"],
            ["id"=>180,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Mirsharai Upazila"],
            ["id"=>181,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Sitakunda Upazila"],
            ["id"=>182,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Sandwip Upazila"],
            ["id"=>183,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Lohagara Upazila"],
            ["id"=>184,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Satkania Upazila"],
            ["id"=>185,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Bashkhali Upazila"],
            ["id"=>186,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Fatikchhari Upazila"],
            ["id"=>187,"division_id"=>2,"district_id"=>43,"bn_name"=>"","name"=>"Rangunia Upazila"],
//======================================================================================================================
//=================================== Cox's Bazar District =============================================================
            /*["id"=>188,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Cox's Bazar sadar Upazila "],
            ["id"=>189,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Eidgah Upazila"],
            ["id"=>190,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Ukhiya Upazila"],
            ["id"=>191,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Teknaf Upazila"],
            ["id"=>192,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Kutubdia Upazila"],
            ["id"=>193,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Ramu Upazila"],
            ["id"=>194,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Chakaria Upazila"],
            ["id"=>195,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Pekua Upazila"],
            ["id"=>196,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Moheskhali Upazila"],*/
//======================================================================================================================
//=================================== Cumilla District =================================================================
            ["id"=>188,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Cumilla Sadar South Upazila"],
            ["id"=>189,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Barura Upazila"],
            ["id"=>190,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Laksam Upazila"],
            ["id"=>191,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Nangolkot Upazila"],
            ["id"=>192,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Lalmai Upazial"],
            ["id"=>193,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Chouddagram Upazila"],
            ["id"=>194,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Homna Upazila"],
            ["id"=>195,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Meghna Upazial"],
            ["id"=>196,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Titash Upazila"],
            ["id"=>197,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Daudkandi Upazila"],
            ["id"=>198,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Burichong Upazila"],
            ["id"=>199,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Brahmanpara Upazila"],
            ["id"=>200,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Muradnagar Upazila"],
            ["id"=>201,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Debidwar UPO"],
            ["id"=>202,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Monohorgonj Upazila"],
            ["id"=>203,"division_id"=>2,"district_id"=>44,"bn_name"=>"","name"=>"Chandina Upazila"],
//======================================================================================================================
//=================================== Cox's Bazar District =============================================================
            ["id"=>204,"division_id"=>2,"district_id"=>45,"bn_name"=>"","name"=>"Cox's Bazar sadar Upazila "],
            ["id"=>205,"division_id"=>2,"district_id"=>45,"bn_name"=>"","name"=>"Eidgah Upazila"],
            ["id"=>206,"division_id"=>2,"district_id"=>45,"bn_name"=>"","name"=>"Ukhiya Upazila"],
            ["id"=>207,"division_id"=>2,"district_id"=>45,"bn_name"=>"","name"=>"Teknaf Upazila"],
            ["id"=>208,"division_id"=>2,"district_id"=>45,"bn_name"=>"","name"=>"Kutubdia Upazila"],
            ["id"=>209,"division_id"=>2,"district_id"=>45,"bn_name"=>"","name"=>"Ramu Upazila"],
            ["id"=>210,"division_id"=>2,"district_id"=>45,"bn_name"=>"","name"=>"Chakaria Upazila"],
            ["id"=>211,"division_id"=>2,"district_id"=>45,"bn_name"=>"","name"=>"Pekua Upazila"],
            ["id"=>212,"division_id"=>2,"district_id"=>45,"bn_name"=>"","name"=>"Moheskhali Upazila"],
//======================================================================================================================
//=================================== Feni District ===================================================================
            ["id"=>213,"division_id"=>2,"district_id"=>46,"bn_name"=>"","name"=>"Feni Sadar Upazila"],
            ["id"=>214,"division_id"=>2,"district_id"=>46,"bn_name"=>"","name"=>"Chagalnaia Upazila"],
            ["id"=>215,"division_id"=>2,"district_id"=>46,"bn_name"=>"","name"=>"Dagonbhuia Upazila"],
            ["id"=>216,"division_id"=>2,"district_id"=>46,"bn_name"=>"","name"=>"Sonagazi Upazila"],
            ["id"=>217,"division_id"=>2,"district_id"=>46,"bn_name"=>"","name"=>"Parshuram Upazila"],
            ["id"=>218,"division_id"=>2,"district_id"=>46,"bn_name"=>"","name"=>"Fulgazi Upazila"],
//======================================================================================================================
//=================================== Khagrachari District =============================================================
            ["id"=>219,"division_id"=>2,"district_id"=>47,"bn_name"=>"","name"=>"Khagrachari Sadar"],
            ["id"=>220,"division_id"=>2,"district_id"=>47,"bn_name"=>"","name"=>"Panchari Upazila"],
            ["id"=>221,"division_id"=>2,"district_id"=>47,"bn_name"=>"","name"=>"Dighinala Upazila"],
            ["id"=>222,"division_id"=>2,"district_id"=>47,"bn_name"=>"","name"=>"Mahalchhari Upazila"],
            ["id"=>223,"division_id"=>2,"district_id"=>47,"bn_name"=>"","name"=>"Ramgor Upazila"],
            ["id"=>224,"division_id"=>2,"district_id"=>47,"bn_name"=>"","name"=>"Guimara Upazila"],
            ["id"=>225,"division_id"=>2,"district_id"=>47,"bn_name"=>"","name"=>"Matiranga Upazila"],
            ["id"=>226,"division_id"=>2,"district_id"=>47,"bn_name"=>"","name"=>"Manikchari Upazila"],
            ["id"=>227,"division_id"=>2,"district_id"=>47,"bn_name"=>"","name"=>"Laxmichari Upazila"],
//======================================================================================================================
//=================================== Lakshmipur District ==============================================================
            ["id"=>228,"division_id"=>2,"district_id"=>48,"bn_name"=>"","name"=>"Lakshmipur Sadar Upazila"],
            ["id"=>229,"division_id"=>2,"district_id"=>48,"bn_name"=>"","name"=>"Raipur Upazila"],
            ["id"=>230,"division_id"=>2,"district_id"=>48,"bn_name"=>"","name"=>"Ramganj Upazila"],
            ["id"=>231,"division_id"=>2,"district_id"=>48,"bn_name"=>"","name"=>"Ramgati Upazila"],
            ["id"=>232,"division_id"=>2,"district_id"=>48,"bn_name"=>"","name"=>"Kamal nagar Upazila"],
//======================================================================================================================
//=================================== Noakhali District ===============================================================
            ["id"=>233,"division_id"=>2,"district_id"=>49,"bn_name"=>"","name"=>"Noakhali Sadar Upazila"],
            ["id"=>234,"division_id"=>2,"district_id"=>49,"bn_name"=>"","name"=>"Suborno Upazila"],
            ["id"=>235,"division_id"=>2,"district_id"=>49,"bn_name"=>"","name"=>"Hatiya Upazila"],
            ["id"=>236,"division_id"=>2,"district_id"=>49,"bn_name"=>"","name"=>"Senbag Upazila"],
            ["id"=>237,"division_id"=>2,"district_id"=>49,"bn_name"=>"","name"=>"Begumganj Upazila"],
            ["id"=>238,"division_id"=>2,"district_id"=>49,"bn_name"=>"","name"=>"Sonaimuri Upazila"],
            ["id"=>239,"division_id"=>2,"district_id"=>49,"bn_name"=>"","name"=>"Kabirhat Upazila"],
            ["id"=>240,"division_id"=>2,"district_id"=>49,"bn_name"=>"","name"=>"Chatkhil Upazila"],
            ["id"=>241,"division_id"=>2,"district_id"=>49,"bn_name"=>"","name"=>"Kompaniganj Upazila"],
//======================================================================================================================
//=================================== Rangamati District ===============================================================
            ["id"=>242,"division_id"=>2,"district_id"=>50,"bn_name"=>"","name"=>"Rangamati Sadar Upazila"],
            ["id"=>243,"division_id"=>2,"district_id"=>50,"bn_name"=>"","name"=>"Rajsthali Upazila"],
            ["id"=>244,"division_id"=>2,"district_id"=>50,"bn_name"=>"","name"=>"Bilaichhori Upazila"],
            ["id"=>245,"division_id"=>2,"district_id"=>50,"bn_name"=>"","name"=>"Kawkhali Upazila"],
            ["id"=>246,"division_id"=>2,"district_id"=>50,"bn_name"=>"","name"=>"Jurachori Upazila"],
            ["id"=>247,"division_id"=>2,"district_id"=>50,"bn_name"=>"","name"=>"Barkal Upazila"],
            ["id"=>248,"division_id"=>2,"district_id"=>50,"bn_name"=>"","name"=>"Langadu Upazila"],
            ["id"=>249,"division_id"=>2,"district_id"=>50,"bn_name"=>"","name"=>"Baghaichari Upazila"],
            ["id"=>250,"division_id"=>2,"district_id"=>50,"bn_name"=>"","name"=>"Kaptai Upazila"],
            ["id"=>251,"division_id"=>2,"district_id"=>50,"bn_name"=>"","name"=>"Naniarchar Upazila"],
//======================================================================================================================
//=================================== Bagerhat District ================================================================
            ["id"=>252,"division_id"=>4,"district_id"=>55,"bn_name"=>"","name"=>"Bagerhat Sadar Upazila"],
            ["id"=>253,"division_id"=>4,"district_id"=>55,"bn_name"=>"","name"=>"Chitalmari Upazila"],
            ["id"=>254,"division_id"=>4,"district_id"=>55,"bn_name"=>"","name"=>"Fakirhat Upazila"],
            ["id"=>255,"division_id"=>4,"district_id"=>55,"bn_name"=>"","name"=>"Mollahat Upazila"],
            ["id"=>256,"division_id"=>4,"district_id"=>55,"bn_name"=>"","name"=>"Kachua Upazila"],
            ["id"=>257,"division_id"=>4,"district_id"=>55,"bn_name"=>"","name"=>"Rampal Upazila"],
            ["id"=>258,"division_id"=>4,"district_id"=>55,"bn_name"=>"","name"=>"Sharankhola Upazila"],
            ["id"=>259,"division_id"=>4,"district_id"=>55,"bn_name"=>"","name"=>"Mongla Upazila"],
            ["id"=>260,"division_id"=>4,"district_id"=>55,"bn_name"=>"","name"=>"Morrelganj Upazila"],
//======================================================================================================================
//=================================== Chuadanga District ===============================================================
            ["id"=>261,"division_id"=>4,"district_id"=>56,"bn_name"=>"","name"=>"Chuadanga Sadar Upazila"],
            ["id"=>262,"division_id"=>4,"district_id"=>56,"bn_name"=>"","name"=>"Alamdanga Upazila"],
            ["id"=>263,"division_id"=>4,"district_id"=>56,"bn_name"=>"","name"=>"Damurhuda Upazila"],
            ["id"=>264,"division_id"=>4,"district_id"=>56,"bn_name"=>"","name"=>"Jibannagar Upazila"],
//======================================================================================================================
//                ["id"=>265,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Upazila Name"]
//=================================== Jessore District =================================================================
            ["id"=>266,"division_id"=>4,"district_id"=>57,"bn_name"=>"","name"=>"Jessore Sadar Upazila"],
            ["id"=>267,"division_id"=>4,"district_id"=>57,"bn_name"=>"","name"=>"Chougachha Upazila"],
            ["id"=>268,"division_id"=>4,"district_id"=>57,"bn_name"=>"","name"=>"Jhikargachha Upazila"],
            ["id"=>269,"division_id"=>4,"district_id"=>57,"bn_name"=>"","name"=>"Sarsa Upazila"],
            ["id"=>270,"division_id"=>4,"district_id"=>57,"bn_name"=>"","name"=>"Monirampur Upazila"],
            ["id"=>271,"division_id"=>4,"district_id"=>57,"bn_name"=>"","name"=>"Keshobpur Upazila"],
            ["id"=>272,"division_id"=>4,"district_id"=>57,"bn_name"=>"","name"=>"Bagharpara Upazila"],
            ["id"=>273,"division_id"=>4,"district_id"=>57,"bn_name"=>"","name"=>"Abhaynagar Upazila"],
            ["id"=>274,"division_id"=>4,"district_id"=>57,"bn_name"=>"","name"=>"Noapara Upazila"],
//======================================================================================================================
//=================================== Jhenaidah District ==============================================================
            ["id"=>275,"division_id"=>4,"district_id"=>58,"bn_name"=>"","name"=>"Jhenaidah Sadar Upazila"],
            ["id"=>276,"division_id"=>4,"district_id"=>58,"bn_name"=>"","name"=>"Horinakundu Upazila"],
            ["id"=>277,"division_id"=>4,"district_id"=>58,"bn_name"=>"","name"=>"Shailakupa Upazila"],
            ["id"=>278,"division_id"=>4,"district_id"=>58,"bn_name"=>"","name"=>"Kotchandpur Upazila"],
            ["id"=>279,"division_id"=>4,"district_id"=>58,"bn_name"=>"","name"=>"Maheshpur Upazila"],
            ["id"=>280,"division_id"=>4,"district_id"=>58,"bn_name"=>"","name"=>"Kaliganj Upazila"],
//======================================================================================================================
//=================================== Khulna District ==================================================================
            ["id"=>281,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Khulna Sadar Thana"],
            ["id"=>282,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Khalishpur Thana"],
            ["id"=>283,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Sonadanga Thana"],
            ["id"=>284,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Doulatpur Thana"],
            ["id"=>285,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Khanjahan Ail Thana"],
            ["id"=>286,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Labanchora Thana"],
            ["id"=>287,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Horintana Thana"],
            ["id"=>288,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Koyra Upazila"],
            ["id"=>289,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Dumuria Upazila"],
            ["id"=>290,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Tarokhada Upazila"],
            ["id"=>291,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Dacope Upazila"],
            ["id"=>292,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Digalia  Upazila"],
            ["id"=>293,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Paikgachha Upazila"],
            ["id"=>294,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Batiaghata Upazila"],
            ["id"=>295,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Phultala Upazila"],
            ["id"=>296,"division_id"=>4,"district_id"=>59,"bn_name"=>"","name"=>"Rupsa Upazila"],
//======================================================================================================================
//=================================== Kushtia District =================================================================
            ["id"=>297,"division_id"=>4,"district_id"=>60,"bn_name"=>"","name"=>"Kushtia Sadar Upazila"],
            ["id"=>298,"division_id"=>4,"district_id"=>60,"bn_name"=>"","name"=>"Kumarkhali Upazila"],
            ["id"=>299,"division_id"=>4,"district_id"=>60,"bn_name"=>"","name"=>"Khoksa Upazila"],
            ["id"=>300,"division_id"=>4,"district_id"=>60,"bn_name"=>"","name"=>"Mirpur Upazila"],
            ["id"=>301,"division_id"=>4,"district_id"=>60,"bn_name"=>"","name"=>"Bheramara Upazila"],
            ["id"=>302,"division_id"=>4,"district_id"=>60,"bn_name"=>"","name"=>"Daulatpur Upazila"],
//======================================================================================================================
//=================================== Magura District ==================================================================
            ["id"=>303,"division_id"=>4,"district_id"=>61,"bn_name"=>"","name"=>"Magura Sadar Upazila"],
            ["id"=>304,"division_id"=>4,"district_id"=>61,"bn_name"=>"","name"=>"Sreepur Upazila"],
            ["id"=>305,"division_id"=>4,"district_id"=>61,"bn_name"=>"","name"=>"Shalikha Upazila"],
            ["id"=>306,"division_id"=>4,"district_id"=>61,"bn_name"=>"","name"=>"Mohammadpur Upazila"],
//======================================================================================================================
//=================================== Meherpur District ===============================================================
            ["id"=>307,"division_id"=>4,"district_id"=>62,"bn_name"=>"","name"=>"Meherpur Sadar Upazila"],
            ["id"=>308,"division_id"=>4,"district_id"=>62,"bn_name"=>"","name"=>"Mujibnagar Upazila"],
            ["id"=>309,"division_id"=>4,"district_id"=>62,"bn_name"=>"","name"=>"Gangni Upazila"],
//======================================================================================================================
//=================================== Narail District ==================================================================
            ["id"=>310,"division_id"=>4,"district_id"=>63,"bn_name"=>"","name"=>"Narail Sadar Upazila"],
            ["id"=>311,"division_id"=>4,"district_id"=>63,"bn_name"=>"","name"=>"Lohagara Upazila"],
            ["id"=>312,"division_id"=>4,"district_id"=>63,"bn_name"=>"","name"=>"Kalia Upazila"],
//======================================================================================================================
//=================================== Satkhira District ===============================================================
            ["id"=>313,"division_id"=>4,"district_id"=>64,"bn_name"=>"","name"=>"Satkhira Upazila"],
            ["id"=>314,"division_id"=>4,"district_id"=>64,"bn_name"=>"","name"=>"Tala Upazila"],
            ["id"=>315,"division_id"=>4,"district_id"=>64,"bn_name"=>"","name"=>"Devhata Upazila"],
            ["id"=>316,"division_id"=>4,"district_id"=>64,"bn_name"=>"","name"=>"Kalaroa Upazila"],
            ["id"=>317,"division_id"=>4,"district_id"=>64,"bn_name"=>"","name"=>"Kaliganj Upazila"],
            ["id"=>318,"division_id"=>4,"district_id"=>64,"bn_name"=>"","name"=>"Shyamnagar Upazila"],
            ["id"=>319,"division_id"=>4,"district_id"=>64,"bn_name"=>"","name"=>"Ashashuni Upazila"],
//======================================================================================================================
//=================================== Bogra District ===================================================================
            ["id"=>320,"division_id"=>5,"district_id"=>18,"bn_name"=>"","name"=>"Bogra Sadar Upazila"],
            ["id"=>321,"division_id"=>5,"district_id"=>18,"bn_name"=>"","name"=>"Adomdighi Upazila"],
            ["id"=>322,"division_id"=>5,"district_id"=>18,"bn_name"=>"","name"=>"Dhunat Upazila"],
            ["id"=>323,"division_id"=>5,"district_id"=>18,"bn_name"=>"","name"=>"Dupchachia Upazila"],
            ["id"=>324,"division_id"=>5,"district_id"=>18,"bn_name"=>"","name"=>"Gabtoli Upazila"],
            ["id"=>325,"division_id"=>5,"district_id"=>18,"bn_name"=>"","name"=>"Kahalu Upazila"],
            ["id"=>326,"division_id"=>5,"district_id"=>18,"bn_name"=>"","name"=>"Nandigram Upazila"],
            ["id"=>327,"division_id"=>5,"district_id"=>18,"bn_name"=>"","name"=>"Sariakandi Upazila"],
            ["id"=>328,"division_id"=>5,"district_id"=>18,"bn_name"=>"","name"=>"Sherpur Upazila"],
            ["id"=>329,"division_id"=>5,"district_id"=>18,"bn_name"=>"","name"=>"Shibgonj Upazila"],
            ["id"=>330,"division_id"=>5,"district_id"=>18,"bn_name"=>"","name"=>"Sonatola Upazila"],
            ["id"=>331,"division_id"=>5,"district_id"=>18,"bn_name"=>"","name"=>"Sajahanpur Upazila"],
//======================================================================================================================
//=================================== Joypurhat District ==============================================================
            ["id"=>332,"division_id"=>5,"district_id"=>19,"bn_name"=>"","name"=>"Joypurhat Sadar Upazila"],
            ["id"=>333,"division_id"=>5,"district_id"=>19,"bn_name"=>"","name"=>"Panchbibi Upazila"],
            ["id"=>334,"division_id"=>5,"district_id"=>19,"bn_name"=>"","name"=>"Kalai Upazila"],
            ["id"=>335,"division_id"=>5,"district_id"=>19,"bn_name"=>"","name"=>"Khetlal Upazila"],
            ["id"=>336,"division_id"=>5,"district_id"=>19,"bn_name"=>"","name"=>"Akkelpur Upazila"],
//======================================================================================================================
//=================================== Naogaon District ===============================================================
            ["id"=>337,"division_id"=>5,"district_id"=>20,"bn_name"=>"","name"=>"Nogaon Sadar Upazila"],
            ["id"=>338,"division_id"=>5,"district_id"=>20,"bn_name"=>"","name"=>"Patnitola Upazila"],
            ["id"=>339,"division_id"=>5,"district_id"=>20,"bn_name"=>"","name"=>"Dhamurhat Upazila"],
            ["id"=>340,"division_id"=>5,"district_id"=>20,"bn_name"=>"","name"=>"Mohadebpur Upazila"],
            ["id"=>341,"division_id"=>5,"district_id"=>20,"bn_name"=>"","name"=>"Porsha Upazila"],
            ["id"=>342,"division_id"=>5,"district_id"=>20,"bn_name"=>"","name"=>"Sapahar Upazila"],
            ["id"=>343,"division_id"=>5,"district_id"=>20,"bn_name"=>"","name"=>"Badalgachi Upazila"],
            ["id"=>344,"division_id"=>5,"district_id"=>20,"bn_name"=>"","name"=>"Manda Upazila"],
            ["id"=>345,"division_id"=>5,"district_id"=>20,"bn_name"=>"","name"=>"Niamotpur Upazila"],
            ["id"=>346,"division_id"=>5,"district_id"=>20,"bn_name"=>"","name"=>"Atrai Upazila"],
            ["id"=>347,"division_id"=>5,"district_id"=>20,"bn_name"=>"","name"=>"Raninagar Upazila"],
//======================================================================================================================
//=================================== Natore District ==================================================================
            ["id"=>348,"division_id"=>5,"district_id"=>21,"bn_name"=>"","name"=>"Natore Sadar Upazila"],
            ["id"=>349,"division_id"=>5,"district_id"=>21,"bn_name"=>"","name"=>"Bagatipara Upazila"],
            ["id"=>350,"division_id"=>5,"district_id"=>21,"bn_name"=>"","name"=>"Boraigram Upazila"],
            ["id"=>351,"division_id"=>5,"district_id"=>21,"bn_name"=>"","name"=>"Gurudaspur Upazila"],
            ["id"=>352,"division_id"=>5,"district_id"=>21,"bn_name"=>"","name"=>"Singra Upazila"],
            ["id"=>353,"division_id"=>5,"district_id"=>21,"bn_name"=>"","name"=>"Noldanga Upazila"],
            ["id"=>354,"division_id"=>5,"district_id"=>21,"bn_name"=>"","name"=>"Lalpur Upazila"],
//======================================================================================================================
//                ["id"=>355,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Chapai Sadar Upazila"],
//                ["id"=>356,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Gamostapur Upazila"],
//                ["id"=>357,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Shibganj Upazila"],
//                ["id"=>358,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Nachol Upazila"],
//                ["id"=>359,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Bholahat Upazila"],
//                ["id"=>360,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Pabna Sadar Upazila"],
//                ["id"=>361,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Atgharia Upazila"],
//                ["id"=>362,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Ishwardi Upazila"],
//                ["id"=>363,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Chatmohar Upazila"],
//                ["id"=>364,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Faridpud Upazila"],
//                ["id"=>365,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Bera Upazila"],
//                ["id"=>366,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Bhangura Upazila"],
//                ["id"=>367,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Santhia Upazila"],
//                ["id"=>368,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Sujanagar Upazila"],
//                ["id"=>369,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Bagha Upazila"],
//                ["id"=>370,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Puthia Upazila"],
//                ["id"=>371,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Poba Upazila"],
//                ["id"=>372,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Baghmara Upazila"],
//                ["id"=>373,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Durgapur Upazila"],
//                ["id"=>374,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Tanore Upazila"],
//                ["id"=>375,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Charghat Upazila"],
//                ["id"=>376,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Godagari Upazila"],
//                ["id"=>377,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Mohonpur Upazila"],
//                ["id"=>378,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"katakhali  Thana"],
//                ["id"=>379,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Motihar Thana"],
//                ["id"=>380,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Rajpara Thana"],
//                ["id"=>381,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kashiadanga Thana"],
//                ["id"=>382,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Boalia Thana"],
//                ["id"=>383,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Shahmokdum Thana"],
//                ["id"=>384,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Chandrima Thana"],
//                ["id"=>385,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Sirajganj Sadar Upazila"],
//                ["id"=>386,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Ullapar Upazila"],
//                ["id"=>387,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kazipur  Upazila"],
//                ["id"=>388,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kamar Khanda Upazila"],
//                ["id"=>389,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Chouhali  Upazila"],
//                ["id"=>390,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Tarash Upazila"],
//                ["id"=>391,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Belkuchi Upazila"],
//                ["id"=>392,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Rayganj Upazila"],
//                ["id"=>393,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Shahjadpur  Upazila"],
//                ["id"=>394,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Hobiganj Sadar Upazila"],
//                ["id"=>395,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Shaestaganj Upazila"],
//                ["id"=>396,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Madhabpur Upazila"],
//                ["id"=>397,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Lakhai Upazila"],
//                ["id"=>398,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Azmireeganj Upazila"],
//                ["id"=>399,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Baniachang Upazila"],
//                ["id"=>400,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Bahubal Upazila"],
//                ["id"=>401,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Chunarughat Upazila"],
//                ["id"=>402,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Nabiganj Upazila"],
//                ["id"=>403,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Moulvibazar Sadar Upazila"],
//                ["id"=>404,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Baralekha Upazila"],
//                ["id"=>405,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kulaura Upazila"],
//                ["id"=>406,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Juri Upazila"],
//                ["id"=>407,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Srimangal Upazila"],
//                ["id"=>408,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kamalganj Upazila"],
//                ["id"=>409,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Rajnagar Upazila"],
//                ["id"=>410,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Sunamganj Sadar Upazila"],
//                ["id"=>411,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Chatak Upazila"],
//                ["id"=>412,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Jagannathpur Upazila"],
//                ["id"=>413,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Tahirpur Upazila"],
//                ["id"=>414,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Jamalganj Upazila"],
//                ["id"=>415,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Shalla Upazila"],
//                ["id"=>416,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Derai Upazila"],
//                ["id"=>417,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Duarabazar Upazila"],
//                ["id"=>418,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Biswombhorpur Upazila"],
//                ["id"=>419,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Santigonj Upazila"],
//                ["id"=>420,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Moddonagar Upazila"],
//                ["id"=>421,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Dormopasha Upazila"],
//                ["id"=>422,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Sylhet sadar Upazila"],
//                ["id"=>423,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Dakshin Surma Upazila"],
//                ["id"=>424,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Fenchuganj Upazila"],
//                ["id"=>425,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Balaganj Upazila"],
//                ["id"=>426,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Osmani Nagar Upazila"],
//                ["id"=>427,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Bishwanath Upazila"],
//                ["id"=>428,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Companiganj Upazila"],
//                ["id"=>429,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Goainghat Upazila"],
//                ["id"=>430,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Jaintapur Upazila"],
//                ["id"=>431,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Golapganj  Upazila"],
//                ["id"=>432,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Beanibazar Upazila"],
//                ["id"=>433,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kanaighat Upazila"],
//                ["id"=>434,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Zakigonj Upazila"],
//                ["id"=>435,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Barguna Sadar Upazila"],
//                ["id"=>436,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Amtali  Upazila"],
//                ["id"=>437,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Amtali Upazila"],
//                ["id"=>438,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Taltali Upazila"],
//                ["id"=>439,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Patharghata Upazila"],
//                ["id"=>440,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Patharghata Upazila"],
//                ["id"=>441,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Bamna Upazila"],
//                ["id"=>442,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Betagi Upazila"],
//                ["id"=>443,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Betagi Upazila"],
//                ["id"=>444,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Barishal Sadar Upazila"],
//                ["id"=>445,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Bakerganj Upazila"],
//                ["id"=>446,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Babuganj Upazila"],
//                ["id"=>447,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Uzirpur Upazila"],
//                ["id"=>448,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Gouranadi Upazila"],
//                ["id"=>449,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Agailzhara Upazila"],
//                ["id"=>450,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Muladi Upazila"],
//                ["id"=>451,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Hizla Upazila"],
//                ["id"=>452,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Hizla Upazila"],
//                ["id"=>453,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Mahendiganj Upazila"],
//                ["id"=>454,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Banaripara Upazila"],
//                ["id"=>455,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Bhola Sadar Upazila"],
//                ["id"=>456,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Doulatkhan Upazila"],
//                ["id"=>457,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Borhanuddin Upazila"],
//                ["id"=>458,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Lalmohan Upazila"],
//                ["id"=>459,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Charfashion Upazila"],
//                ["id"=>460,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Tojumoddin Upazila"],
//                ["id"=>461,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Monpura Upazila"],
//                ["id"=>462,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Jhalokathi Sadar Upazila"],
//                ["id"=>463,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Rajapur Upazila"],
//                ["id"=>464,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Nalchhiti Upazila"],
//                ["id"=>465,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Nalchhiti Upazila"],
//                ["id"=>466,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kathalia Upazila"],
//                ["id"=>467,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Patuakhali sadar Upazila"],
//                ["id"=>468,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Dumki Upazila"],
//                ["id"=>469,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Mirzaganj Upazila"],
//                ["id"=>470,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Bauphal Upazila"],
//                ["id"=>471,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Dashmina Upazila"],
//                ["id"=>472,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Galachipa Upazila"],
//                ["id"=>473,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Rangabali Upazila"],
//                ["id"=>474,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kalapara Upazila"],
//                ["id"=>475,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Pirojpur Sadar Upazila"],
//                ["id"=>476,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Indurkani Upazila"],
//                ["id"=>477,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kaukhali Upazila"],
//                ["id"=>478,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Swarupkathi Upazila"],
//                ["id"=>479,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Nasarabad Upazila"],
//                ["id"=>480,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Nazirpur Upazila"],
//                ["id"=>481,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Bhandaria Upazila"],
//                ["id"=>482,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Mathbaria Upazila"],
//                ["id"=>483,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Jamalpur Sadar Upazila"],
//                ["id"=>484,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Melandaha Upazila"],
//                ["id"=>485,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Islampur Upazila"],
//                ["id"=>486,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Dewanganj Upazila"],
//                ["id"=>487,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Madarganj Upazila"],
//                ["id"=>488,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Sarishabari Upazila"],
//                ["id"=>489,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Bakshigonj Upazila"],
//                ["id"=>490,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Mymensingh sadar Upazila"],
//                ["id"=>491,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Muktagachha Upazila"],
//                ["id"=>492,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Fulbaria Upazila"],
//                ["id"=>493,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Trishal Upazila"],
//                ["id"=>494,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Gaforgaon Upazila"],
//                ["id"=>495,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Bhaluka Upazila"],
//                ["id"=>496,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Phulpur  Upazila"],
//                ["id"=>497,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Tarakanda Upazila"],
//                ["id"=>498,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Haluaghat Upazila"],
//                ["id"=>499,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Gouripur Upazila"],
//                ["id"=>500,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Isshwargonj Upazila"],
//                ["id"=>501,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Dhobaura Upazila"],
//                ["id"=>502,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Nandail UPO"],
//                ["id"=>503,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Netrakona Sadar Upazila"],
//                ["id"=>504,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Purbadhola Upazila"],
//                ["id"=>505,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Susung Durgapur"],
//                ["id"=>506,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kalmakanda "],
//                ["id"=>507,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Barhatta Upazila"],
//                ["id"=>508,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Mohanganj Upazila"],
//                ["id"=>509,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Khaliajuri Upazila"],
//                ["id"=>510,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Atpara Upazila"],
//                ["id"=>511,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kendua Upazila"],
//                ["id"=>512,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Madan Upazila"],
//                ["id"=>513,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Sherpur Sadar Upazila"],
//                ["id"=>514,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Nalitabari Upazila"],
//                ["id"=>515,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Jhinaigati Upazila"],
//                ["id"=>516,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Shribardi Upazila"],
//                ["id"=>517,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Nakla Upazila"],
//                ["id"=>518,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Dinajpur Thana"],
//                ["id"=>519,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Parbatipur Upazila"],
//                ["id"=>520,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Birampur Upazila"],
//                ["id"=>521,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Birganj Upazila"],
//                ["id"=>522,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Biral Upazila"],
//                ["id"=>523,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Bachaganj Upazila"],
//                ["id"=>524,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Chrirbandar Upazila"],
//                ["id"=>525,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Phulbari Upazila"],
//                ["id"=>526,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Ghoraghat Upazila"],
//                ["id"=>527,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Hakimpur Upazila"],
//                ["id"=>528,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kaharole Upazila"],
//                ["id"=>529,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Khansama Upazila"],
//                ["id"=>530,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Nababganj Upazila"],
//                ["id"=>531,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Gaibandha Sadar Upazila"],
//                ["id"=>532,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Phulchari Upazila"],
//                ["id"=>533,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Gobindoganj  Upazila"],
//                ["id"=>534,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Palashbsri Upazila"],
//                ["id"=>535,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Saghata Upazila"],
//                ["id"=>536,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Sundarganj Upazila"],
//                ["id"=>537,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Saadullapur Upazila"],
//                ["id"=>538,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kurigram ‍Sadar Upazila"],
//                ["id"=>539,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Bhurungamari Upazila"],
//                ["id"=>540,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Ulipur Upazila"],
//                ["id"=>541,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Chilmari Upazila"],
//                ["id"=>542,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Phulbari Upazila"],
//                ["id"=>543,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Rajarhat Upazila"],
//                ["id"=>544,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Nageshwari Upazila"],
//                ["id"=>545,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Roumari Upazila"],
//                ["id"=>546,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Rajibpur Upazila"],
//                ["id"=>547,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Lalmonirhat Sadar Upazila"],
//                ["id"=>548,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Aditmari Upazila"],
//                ["id"=>549,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Hatibandha Upazila"],
//                ["id"=>550,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kaliganj Upazila"],
//                ["id"=>551,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"patgram Upazila"],
//                ["id"=>552,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Nilphamari ‍Sadar Upazila"],
//                ["id"=>553,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Dimla Upazila"],
//                ["id"=>554,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Domar Upazila"],
//                ["id"=>555,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Jaldhaka Upazila"],
//                ["id"=>556,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kishoriganj Upazila"],
//                ["id"=>557,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Syedpur Upazila"],
//                ["id"=>558,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Panchagarh  Upazila"],
//                ["id"=>559,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Boda Upazila"],
//                ["id"=>560,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Dabiganj Upazila"],
//                ["id"=>561,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Atwari Upazila"],
//                ["id"=>562,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Telulia Upazila"],
//                ["id"=>563,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Rangpur Sadar Upazila"],
//                ["id"=>564,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Gangachara Upazila"],
//                ["id"=>565,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Badarganj Upazila"],
//                ["id"=>566,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Kaunia Upazila"],
//                ["id"=>567,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Mithapukur Upazila"],
//                ["id"=>568,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Pirganj Upazila"],
//                ["id"=>569,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Pirgacha Upazila"],
//                ["id"=>570,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Taraganj Upazila"],
//                ["id"=>571,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Thakurgaon Upazila"],
//                ["id"=>572,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Baliadangi Upazila"],
//                ["id"=>573,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Horipur Upazila"],
//                ["id"=>574,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Pirganj Upazila"],
//                ["id"=>575,"division_id"=>,"district_id"=>,"bn_name"=>"","name"=>"Rani Sankail Upazila"],;
        ];
//        return json_decode($data, true);
        return $data;
    }
}
